- hosts: localhost
  gather_facts: no
  handlers:
  - include_tasks: handlers/handlers.yml

  tasks:
  - name: task with "notify"
    debug:
      msg: "this task should run handler"
    notify: handler1
    changed_when: true


