- hosts: localhost
  gather_facts: no
  tasks:
  - name: task with "notify"
    debug:
      msg: "this task should run handler"
    notify: my handler1
    changed_when: true
    tags: 
      - always
      - task_tag1
      - task_tag2
      - never



  - name: second task
    debug:
      msg: "do something"


  handlers:
  - name: my handler1
    debug: 
      msg: "its handler1 time!"
    tags: never

    